//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapadeDatos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=Base_Datos_Hotel_APM_Grand;Integrated Secur" +
            "ity=True;Encrypt=True;TrustServerCertificate=True")]
        public string Base_Datos_Hotel_APM_GrandConnectionString {
            get {
                return ((string)(this["Base_Datos_Hotel_APM_GrandConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-4K6RV9V2;Initial Catalog=Base_Datos_Hotel_APM_Grand;Integrated" +
            " Security=True;Encrypt=True;TrustServerCertificate=True")]
        public string Base_Datos_Hotel_APM_GrandConnectionString1 {
            get {
                return ((string)(this["Base_Datos_Hotel_APM_GrandConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CF2J6U8;Initial Catalog=\"base de datos 2\";Persist Security In" +
            "fo=True;User ID=sa;Password=1234;Encrypt=True;TrustServerCertificate=True")]
        public string base_de_datos_2ConnectionString {
            get {
                return ((string)(this["base_de_datos_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-23BPHEQS;Initial Catalog=Base_Datos_Hotel_APM_Grand;Integrated" +
            " Security=True;TrustServerCertificate=True")]
        public string Base_Datos_Hotel_APM_GrandConnectionString2 {
            get {
                return ((string)(this["Base_Datos_Hotel_APM_GrandConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-23BPHEQS;Initial Catalog=Base_Datos_Hotel_APM_Grand;Integrated" +
            " Security=True;Encrypt=True;TrustServerCertificate=True")]
        public string Base_Datos_Hotel_APM_GrandConnectionString3 {
            get {
                return ((string)(this["Base_Datos_Hotel_APM_GrandConnectionString3"]));
            }
        }
    }
}
